// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 0
#define MINOR_VERSION 0
#define REVISION 1

#define BUILD_NUMBER 11
#define COMMIT_HASH "28f1e09bf72aeb2f1b1b60fe06951837dca70aec"

#endif // VERSION_AUTOGEN_H
