// This file is auto-generated by CMake
// Any changes made to this file will be lost
// Set major, minor and revision numbers in the root CMakeLists.txt file

#ifndef VERSION_AUTOGEN_H
#define VERSION_AUTOGEN_H

#define CMAKE_GENERATED_VERSION

#define MAJOR_VERSION 0
#define MINOR_VERSION 0
#define REVISION 1

#define BUILD_NUMBER 23
#define COMMIT_HASH "9b3a624d7d4bed38b788e41ad2cdcd23b08a1309"

#endif // VERSION_AUTOGEN_H
